version: "3"
services:
  strapi:
    container_name: ${APP_NAME}
    image: test
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PORT: 3306
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./node_modules:/opt/app/node_modules
      - ./yarn.lock:/opt/app/yarn.lock
      - ./package.json:/opt/app/package.json
      - ./public:/opt/app/public
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./.env:/opt/app/.env
    ports:
      - "1337:1337"
    depends_on:
      - mysql

  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    container_name: strapi-v4-db
    restart: unless-stopped
    environment:
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
    volumes:
      - ./mysql_data:/var/lib/mysql
